@switch($article->category_id)
@case(68)
@include('www.pages.town.detail.features.cate-68')
@break
@case(69)
@case(71)
@case(75)
@include('www.pages.town.detail.features.cate-69')
@break
@case(70)
@include('www.pages.town.detail.features.cate-70')
@break
@case(72)
@include('www.pages.town.detail.features.cate-72')
@break
@case(74)
@include('www.pages.town.detail.features.cate-74')
@break
@case(76)
@include('www.pages.town.detail.features.cate-76')
@break
@case(77)
@include('www.pages.town.detail.features.cate-77')
@break
@case(78)
@include('www.pages.town.detail.features.cate-78')
@break
@default

@endswitch